import { format, resolveConfig } from "prettier"
import { ESLint } from "eslint"
import { readFileSync, writeFileSync } from "node:fs"
import { execFileSync } from "node:child_process"
import Transpiler from "three/addons/transpiler/Transpiler.js"
import GLSLDecoder from "three/addons/transpiler/GLSLDecoder.js"
import TSLEncoder from "three/addons/transpiler/TSLEncoder.js"

const linter = new ESLint({ fix: true })
const prettierOptions = await resolveConfig("src/shaders/generated/screen.js")

// Offline conversion only: neither the parser nor GLSL enters the client bundle.
const inputs = [
  ["screen", "src/shaders/material-screen/fragment.glsl"],
  ["bloom", "src/shaders/material-bloom/fragment.glsl"],
  ["postprocessing", "src/shaders/material-postprocessing/fragment.glsl"],
  ["not-found", "src/shaders/material-not-found/fragment.glsl"],
  ["sky", "src/shaders/material-sky/fragment.glsl"],
  ["sky-lut", "src/shaders/material-sky/lut-fragment.glsl"],
  ["steam", "src/shaders/material-steam/fragment.glsl"],
  ["routing", "src/components/routing-element/frag.glsl"],
  ["doom", "src/shaders/material-doom/fragment.glsl"]
]
for (const [name, path, extract] of inputs) {
  let source = readFileSync(path, "utf8")
  if (extract) {
    source = source.match(extract)?.[1]
    if (!source) throw new Error("Cannot find shader " + path)
  }
  source = source.replace(/#include <colorspace_fragment>/g, "")
  source = source.replace(/precision\s+\w+\s+\w+\s*;/g, "")
  if (name === "doom") {
    // TSL function layout arguments are value nodes, not TextureNodes.
    // Capture the texture binding rather than passing a sampler parameter.
    source = source
      .replace("sampler2D tex, ", "")
      .replaceAll("texture2D(tex,", "texture2D(uTexture,")
      .replace("chromaticAberration(uTexture, uv,", "chromaticAberration(uv,")
  }
  // These two shaders return from the first conditional in main. Express the
  // rest as its else branch so a JS callback return cannot swallow a GLSL return.
  if (name === "bloom" || name === "doom") {
    source = source.replace(/return;\s*\}/, "} else {")
    const end = source.lastIndexOf("}")
    source = source.slice(0, end) + "}\n" + source.slice(end)
  }
  source = execFileSync("clang", ["-E", "-P", "-x", "c", "-"], {
    input: source
  }).toString()
  source = source
    .replace(
      /void main\s*\(\s*\)\s*\{/,
      "vec4 main() { vec4 gl_FragColor = vec4(0.0);"
    )
    .replace(/return\s*;/g, "return gl_FragColor;")
  const end = source.lastIndexOf("}")
  source = source.slice(0, end) + "return gl_FragColor;\n" + source.slice(end)
  const e = new TSLEncoder()
  e.reference = true
  let code = new Transpiler(new GLSLDecoder(), e).parse(source)
  code = code.replace(/- (\d+\.\d+)\.(mul|add|sub|div)\(/g, "float(-$1).$2(")
  // Numeric TSL matrix constructors use Three's row-major constructor API;
  // GLSL source lists columns. Preserve the original element ordering.
  code = code.replace(
    /mat([234])\( ([\d.,\s+-]+) \)/g,
    (all, dimension, body) => {
      const n = Number(dimension),
        values = body.split(",").map((v) => v.trim())
      if (values.length !== n * n) return all
      return `mat${n}( ${values.map((_, i) => values[(i % n) * n + Math.floor(i / n)]).join(", ")} )`
    }
  )
  code = code.replace(/^const gl_FragCoord = [^;]+;$/gm, "")
  // r186's linker misses mutations through swizzles and nested loops. Make
  // function-local values explicit variables, also preventing duplicated work.
  code = code.replace(/^([ \t]+const \w+ = [^;\n]+)(;)$/gm, (all, decl, end) =>
    decl.includes(".toVar()") ? all : decl + ".toVar()" + end
  )
  code = code.replace(
    /const (\w+) = varying\([^;]+;/g,
    (_, n) => `const ${n} = bindings.${n};`
  )
  code = code
    .replace(/export const /g, "const ")
    .replace(/\{ , return:/g, "{ return:")
  code = code.replace(/\}, \{ return: '[^']+' \} \)/g, "})")
  if (name === "doom") {
    // Inline helpers that capture a sampler. Standalone function layouts cannot
    // safely lift that TextureNode's bindings into both backend function scopes.
    code = code.replace(/\}, \{ [^\n]+return: '[^']+' \} \)/g, "})")
  }
  const imports = code.match(/^import[^;]+;$/gm)?.join("\n") ?? ""
  code = code.replace(/^import[^;]+;$/gm, "")
  code = code.replace(
    /reference\( 'value', '([^']+)', uniforms\[ '([^']+)' \] \)/g,
    (_, type, key) => `bindUniform(uniforms, '${key}', '${type}')`
  )
  writeFileSync(
    `src/shaders/generated/${name}.js`,
    await format(
      `// Generated by scripts/graphics/generate-tsl.mjs; edit the source shader and regenerate.\n${imports}\nimport { bindUniform, fragmentBindings } from '@/lib/graphics/material';\nexport function createShader(uniforms, overrides = {}) {\nconst bindings = { ...fragmentBindings, ...overrides };\nconst gl_FragCoord = bindings.gl_FragCoord;\n${code}\nreturn main();\n}\n`,
      { ...prettierOptions, parser: "babel" }
    )
  )
  const filePath = `src/shaders/generated/${name}.js`
  const [linted] = await linter.lintText(readFileSync(filePath, "utf8"), {
    filePath
  })
  if (linted.output) writeFileSync(filePath, linted.output)
  console.log("Generated", name)
}
